[package]
name = "serde_rayon_clap_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rayon = "1.5"
clap = "2.33"
serde_yaml = "0.8"

